// @ts-check

/**
 * Generated from the folder structure rather than listed by hand: a page that
 * exists should be reachable, and a hand-kept sidebar is where that stops
 * being true.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
